# gen_forwarders.ps1
# This is just a script to generate the forwarders for winhttp.dll yourself 
# so you don't need to rely on the bundled one in the repo. Entirely optional,
# the bundled dll will work fine if you trust it. 
#   powershell -ExecutionPolicy Bypass -File gen_forwarders.ps1
# ============================================================================
param(
    [string]$Dll = "$env:WINDIR\System32\winhttp.dll",
    [string]$Out = (Join-Path $PSScriptRoot 'src\forwarders.g.h')
)

if (-not (Test-Path $Dll)) { throw "winhttp.dll not found at $Dll" }
$b = [IO.File]::ReadAllBytes($Dll)

function U16($o) { [BitConverter]::ToUInt16($b, $o) }
function U32($o) { [BitConverter]::ToUInt32($b, $o) }

$pe = U32 0x3C
if ((U32 $pe) -ne 0x00004550) { throw 'Not a PE file (bad NT signature)' }
$optStart = $pe + 24
$magic = U16 $optStart
$ddStart = if ($magic -eq 0x20b) { $optStart + 112 } else { $optStart + 96 }
$expRva = U32 $ddStart
$numSec = U16 ($pe + 6)
$optSize = U16 ($pe + 20)
$secStart = $optStart + $optSize

$secs = @()
for ($i = 0; $i -lt $numSec; $i++) {
    $o = $secStart + $i * 40
    $secs += [pscustomobject]@{ V = (U32 ($o + 12)); S = (U32 ($o + 16)); P = (U32 ($o + 20)) }
}
function R2O($rva) {
    foreach ($s in $secs) { if ($rva -ge $s.V -and $rva -lt ($s.V + $s.S)) { return $rva - $s.V + $s.P } }
    throw "RVA 0x$("{0:X}" -f $rva) not in any section"
}
function RStr($rva) {
    $o = R2O $rva; $sb = New-Object Text.StringBuilder
    while ($b[$o] -ne 0) { [void]$sb.Append([char]$b[$o]); $o++ }
    $sb.ToString()
}

$expOff = R2O $expRva
$nNames = U32 ($expOff + 24)
$namesRva = U32 ($expOff + 32)
$namesOff = R2O $namesRva

$names = for ($i = 0; $i -lt $nNames; $i++) { RStr (U32 ($namesOff + $i * 4)) }
$names = $names | Sort-Object -Unique

$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine('// forwarders.g.h  - GENERATED by gen_forwarders.ps1, do not edit by hand.')
[void]$sb.AppendLine('// ----------------------------------------------------------------------------')
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#define FWD(name) \')
[void]$sb.AppendLine('    __pragma(comment(linker, "/export:" #name "=C:\\Windows\\System32\\winhttp.dll." #name))')
[void]$sb.AppendLine('')
foreach ($n in $names) { [void]$sb.AppendLine("FWD($n)") }
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#undef FWD')

[IO.File]::WriteAllText($Out, $sb.ToString(), [Text.Encoding]::ASCII)
Write-Host "Wrote $($names.Count) forwarders to $Out"
